on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: npm install, build and test
        run: |
          npm install
          npm run build 
          



    
