on:
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  my_job:
    name: deploy to staging
    runs-on: ubuntu-18.04

    steps:
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'

      - name: npm install, build and test
        run: |
          npm install
          npm run build 
          



    
